xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    EF RUSSIAN 20 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR:
      dims: []
      attrs: {}
      data: 0.008497659116983414
    EF RUSSIAN 20 PRECIP-INC SCREENED:
      dims: []
      attrs: {}
      data: 0.02247573435306549
    NR CALPELLA FLOW COE CPL:
      dims: []
      attrs: {}
      data: 522.99658203125
    POTTER VALLEY CA FLOW USGS_ADJUSTED:
      dims: []
      attrs: {}
      data: 97.95722961425781
    UKIAH CA HUMIDITY USAF-NOAA:
      dims: []
      attrs: {}
      data: 22.655588150024414
    UKIAH CA SOLAR RADIATION USAF-NOAA:
      dims: []
      attrs: {}
      data: 300.0357360839844
    UKIAH CA TEMPERATURE USAF-NOAA:
      dims: []
      attrs: {}
      data: 14.651581764221191
    UKIAH CA WINDSPEED USAF-NOAA:
      dims: []
      attrs: {}
      data: 4.3032708168029785
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    EF RUSSIAN 20 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR:
      dims: []
      attrs: {}
      data: 0.005148180294781923
    EF RUSSIAN 20 PRECIP-INC SCREENED:
      dims: []
      attrs: {}
      data: 0.004315690137445927
    NR CALPELLA FLOW COE CPL:
      dims: []
      attrs: {}
      data: 331.2980041503906
    POTTER VALLEY CA FLOW USGS_ADJUSTED:
      dims: []
      attrs: {}
      data: 173.14883422851562
    UKIAH CA HUMIDITY USAF-NOAA:
      dims: []
      attrs: {}
      data: 65.5623779296875
    UKIAH CA SOLAR RADIATION USAF-NOAA:
      dims: []
      attrs: {}
      data: 205.0643768310547
    UKIAH CA TEMPERATURE USAF-NOAA:
      dims: []
      attrs: {}
      data: 57.97175979614258
    UKIAH CA WINDSPEED USAF-NOAA:
      dims: []
      attrs: {}
      data: 3.876985788345337
