# UCB_training/constants.py
# Central place for exact feature names used by each basin (daily resolution).
# Keep strings EXACT (case/spacing) to match CSV headers.

ALL_BASINS = ("calpella", "guerneville", "hopland", "warm_springs")

# ---- Targets -----------------------------------------------------------------

TARGET_BY_BASIN = {
    "calpella":      "NR CALPELLA FLOW COE CPL",
    "guerneville":   "NR GUERNEVILLE FLOW COE GRN",
    "hopland":       "NR HOPLAND FLOW COE HOP",
    "warm_springs":  "LAKE SONOMA FLOW-RES IN CALC-VAL-SHIFT-SMOOTH",
}

# ---- Baseline (NO-PHYSICS) dynamic inputs, from your YAMLs -------------------

NO_PHYSICS_INPUTS_DAILY_BY_BASIN = {
    "calpella": [
        "EF RUSSIAN 20 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "EF RUSSIAN 20 PRECIP-INC SCREENED",
        "POTTER VALLEY CA FLOW USGS_ADJUSTED",
        "UKIAH CA HUMIDITY USAF-NOAA",
        "UKIAH CA SOLAR RADIATION USAF-NOAA",
        "UKIAH CA TEMPERATURE USAF-NOAA",
        "UKIAH CA WINDSPEED USAF-NOAA",
    ],

    "guerneville": [
        # ET (RUN:BASIN AVERAGE 60 YR)
        "BIG SULPHUR CR ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "DRY CREEK 10 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "EF RUSSIAN 20 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "GREEN VALLEY ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "LAGUNA ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "RUSSIAN 20 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "RUSSIAN 30 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "RUSSIAN 40 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "RUSSIAN 50 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "RUSSIAN 60 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "RUSSIAN 70 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "SANTA ROSA CR 10 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "SANTA ROSA CR 20 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "WF RUSSIAN ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        # Precip
        "BIG SULPHUR CR PRECIP-INC SCREENED",
        "DRY CREEK 10 PRECIP-INC SCREENED",
        "EF RUSSIAN 20 PRECIP-INC SCREENED",
        "GREEN VALLEY PRECIP-INC SCREENED",
        "LAGUNA PRECIP-INC SCREENED",
        "RUSSIAN 20 PRECIP-INC SCREENED",
        "RUSSIAN 30 PRECIP-INC SCREENED",
        "RUSSIAN 40 PRECIP-INC SCREENED",
        "RUSSIAN 50 PRECIP-INC SCREENED",
        "RUSSIAN 60 PRECIP-INC SCREENED",
        "RUSSIAN 70 PRECIP-INC SCREENED",
        "SANTA ROSA CR 10 PRECIP-INC SCREENED",
        "SANTA ROSA CR 20 PRECIP-INC SCREENED",
        "WF RUSSIAN PRECIP-INC SCREENED",
        # Met (UKIAH + SANTA ROSA)
        "UKIAH CA HUMIDITY USAF-NOAA",
        "UKIAH CA SOLAR RADIATION USAF-NOAA",
        "UKIAH CA TEMPERATURE USAF-NOAA",
        "UKIAH CA WINDSPEED USAF-NOAA",
        "SANTA ROSA CA HUMIDITY USAF-NOAA",
        "SANTA ROSA CA SOLAR RADIATION USAF-NOAA",
        "SANTA ROSA CA TEMPERATURE USAF-NOAA",
        "SANTA ROSA CA WINDSPEED USAF-NOAA",
        # Boundary conditions
        "UKIAH CA FLOW USGS-MERGED",
        "GEYSERVILLE CA FLOW USGS-MERGED",
    ],

    "hopland": [
        "RUSSIAN 60 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "RUSSIAN 60 PRECIP-INC SCREENED",
        "RUSSIAN 70 PRECIP-INC SCREENED",
        "RUSSIAN 70 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "WF RUSSIAN PRECIP-INC SCREENED",
        "WF RUSSIAN ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "UKIAH CA HUMIDITY USAF-NOAA",
        "UKIAH CA SOLAR RADIATION USAF-NOAA",
        "UKIAH CA TEMPERATURE USAF-NOAA",
        "UKIAH CA WINDSPEED USAF-NOAA",
        "UKIAH CA FLOW USGS-MERGED",
    ],

    "warm_springs": [
        "DRY CREEK 20 PRECIP-INC SCREENED",
        "DRY CREEK 20 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "DRY CREEK 30 PRECIP-INC SCREENED",
        "DRY CREEK 30 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR",
        "UKIAH CA HUMIDITY USAF-NOAA",
        "UKIAH CA SOLAR RADIATION USAF-NOAA",
        "UKIAH CA TEMPERATURE USAF-NOAA",
        "UKIAH CA WINDSPEED USAF-NOAA",
        "SANTA ROSA CA HUMIDITY USAF-NOAA",
        "SANTA ROSA CA SOLAR RADIATION USAF-NOAA",
        "SANTA ROSA CA TEMPERATURE USAF-NOAA",
        "SANTA ROSA CA WINDSPEED USAF-NOAA",
    ],
}

# ---- Physics-only inputs (EXTRA variables; do NOT duplicate the baseline list) -

PHYSICS_ONLY_INPUTS_DAILY_BY_BASIN = {
    "calpella": [
        "Capella Gage FLOW",
        "EF Russian 20 ET-POTENTIAL",
        "EF Russian 20 FLOW",
        "EF Russian 20 FLOW-BASE",
        "EF Russian 20 INFILTRATION",
        "EF Russian 20 PERC-SOIL",
        "EF Russian 20 SATURATION FRACTION",
    ],

    "guerneville": [
        "Guerneville Gage FLOW",
        "Big Sulphur Cr ET-POTENTIAL",
        "Big Sulphur Cr FLOW",
        "Big Sulphur Cr FLOW-BASE",
        "Big Sulphur Cr INFILTRATION",
        "Big Sulphur Cr PERC-SOIL",
        "Big Sulphur Cr SATURATION FRACTION",
        "Dry Creek 10 ET-POTENTIAL",
        "Dry Creek 10 FLOW",
        "Dry Creek 10 FLOW-BASE",
        "Dry Creek 10 INFILTRATION",
        "Dry Creek 10 PERC-SOIL",
        "Dry Creek 10 SATURATION FRACTION",
        "Green Valley ET-POTENTIAL",
        "Green Valley FLOW",
        "Green Valley FLOW-BASE",
        "Green Valley INFILTRATION",
        "Green Valley PERC-SOIL",
        "Green Valley SATURATION FRACTION",
        "Laguna ET-POTENTIAL",
        "Laguna FLOW",
        "Laguna FLOW-BASE",
        "Laguna INFILTRATION",
        "Laguna PERC-SOIL",
        "Laguna SATURATION FRACTION",
        "Russian 20 ET-POTENTIAL",
        "Russian 20 FLOW",
        "Russian 20 FLOW-BASE",
        "Russian 20 INFILTRATION",
        "Russian 20 PERC-SOIL",
        "Russian 20 SATURATION FRACTION",
        "Russian 30 ET-POTENTIAL",
        "Russian 30 FLOW",
        "Russian 30 FLOW-BASE",
        "Russian 30 INFILTRATION",
        "Russian 30 PERC-SOIL",
        "Russian 30 SATURATION FRACTION",
        "Russian 40 ET-POTENTIAL",
        "Russian 40 FLOW",
        "Russian 40 FLOW-BASE",
        "Russian 40 INFILTRATION",
        "Russian 40 PERC-SOIL",
        "Russian 40 SATURATION FRACTION",
        "Russian 50 ET-POTENTIAL",
        "Russian 50 FLOW",
        "Russian 50 FLOW-BASE",
        "Russian 50 INFILTRATION",
        "Russian 50 PERC-SOIL",
        "Russian 50 SATURATION FRACTION",
        "Russian 60 ET-POTENTIAL",
        "Russian 60 FLOW",
        "Russian 60 FLOW-BASE",
        "Russian 60 INFILTRATION",
        "Russian 60 PERC-SOIL",
        "Russian 60 SATURATION FRACTION",
        "Russian 70 ET-POTENTIAL",
        "Russian 70 FLOW",
        "Russian 70 FLOW-BASE",
        "Russian 70 INFILTRATION",
        "Russian 70 PERC-SOIL",
        "Russian 70 SATURATION FRACTION",
        "Santa Rosa Cr 10 ET-POTENTIAL",
        "Santa Rosa Cr 10 FLOW",
        "Santa Rosa Cr 10 FLOW-BASE",
        "Santa Rosa Cr 10 INFILTRATION",
        "Santa Rosa Cr 10 PERC-SOIL",
        "Santa Rosa Cr 10 SATURATION FRACTION",
        "Santa Rosa Cr 20 ET-POTENTIAL",
        "Santa Rosa Cr 20 FLOW",
        "Santa Rosa Cr 20 FLOW-BASE",
        "Santa Rosa Cr 20 INFILTRATION",
        "Santa Rosa Cr 20 PERC-SOIL",
        "Santa Rosa Cr 20 SATURATION FRACTION",
        "WF Russian ET-POTENTIAL",
        "WF Russian FLOW",
        "WF Russian FLOW-BASE",
        "WF Russian INFILTRATION",
        "WF Russian PERC-SOIL",
        "WF Russian SATURATION FRACTION",
    ],

    "hopland": [
        "Hopland Gage FLOW",
        "Russian 60 ET-POTENTIAL",
        "Russian 60 FLOW",
        "Russian 60 FLOW-BASE",
        "Russian 60 INFILTRATION",
        "Russian 60 PERC-SOIL",
        "Russian 60 SATURATION FRACTION",
        "Russian 70 ET-POTENTIAL",
        "Russian 70 FLOW",
        "Russian 70 FLOW-BASE",
        "Russian 70 INFILTRATION",
        "Russian 70 PERC-SOIL",
        "Russian 70 SATURATION FRACTION",
        "WF Russian ET-POTENTIAL",
        "WF Russian FLOW",
        "WF Russian FLOW-BASE",
        "WF Russian INFILTRATION",
        "WF Russian PERC-SOIL",
        "WF Russian SATURATION FRACTION",
        # (Intentionally NOT including the UKIAH* and *USGS-MERGED items; they are baseline.)
        # (Intentionally NOT including "Lake Mendocino Storage" since it was commented out.)
    ],

    "warm_springs": [
        "Dry Creek 20 ET-POTENTIAL",
        "Dry Creek 20 FLOW",
        "Dry Creek 20 FLOW-BASE",
        "Dry Creek 20 INFILTRATION",
        "Dry Creek 20 PERC-SOIL",
        "Dry Creek 20 SATURATION FRACTION",
        "Dry Creek 30 ET-POTENTIAL",
        "Dry Creek 30 FLOW",
        "Dry Creek 30 FLOW-BASE",
        "Dry Creek 30 INFILTRATION",
        "Dry Creek 30 PERC-SOIL",
        "Dry Creek 30 SATURATION FRACTION",
        "Warm Springs Dam Inflow FLOW",
        # (Intentionally NOT including UKIAH/SANTA ROSA met gauges here; those are baseline.)
    ],
}


FEATURES_WITH_PHYSICS_DAILY_BY_BASIN = {
    b: NO_PHYSICS_INPUTS_DAILY_BY_BASIN[b] + PHYSICS_ONLY_INPUTS_DAILY_BY_BASIN[b]
    for b in ALL_BASINS
}