xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    EF RUSSIAN 20 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR:
      dims: []
      attrs: {}
      data: 0.008325697854161263
    EF RUSSIAN 20 PRECIP-INC SCREENED:
      dims: []
      attrs: {}
      data: 0.024147840216755867
    NR CALPELLA FLOW COE CPL:
      dims: []
      attrs: {}
      data: 572.6403198242188
    POTTER VALLEY CA FLOW USGS_ADJUSTED:
      dims: []
      attrs: {}
      data: 96.53587341308594
    UKIAH CA HUMIDITY USAF-NOAA:
      dims: []
      attrs: {}
      data: 22.220266342163086
    UKIAH CA SOLAR RADIATION USAF-NOAA:
      dims: []
      attrs: {}
      data: 294.5306091308594
    UKIAH CA TEMPERATURE USAF-NOAA:
      dims: []
      attrs: {}
      data: 14.4025297164917
    UKIAH CA WINDSPEED USAF-NOAA:
      dims: []
      attrs: {}
      data: 4.300138473510742
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    EF RUSSIAN 20 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR:
      dims: []
      attrs: {}
      data: 0.005002184771001339
    EF RUSSIAN 20 PRECIP-INC SCREENED:
      dims: []
      attrs: {}
      data: 0.004815222695469856
    NR CALPELLA FLOW COE CPL:
      dims: []
      attrs: {}
      data: 366.2117004394531
    POTTER VALLEY CA FLOW USGS_ADJUSTED:
      dims: []
      attrs: {}
      data: 184.90768432617188
    UKIAH CA HUMIDITY USAF-NOAA:
      dims: []
      attrs: {}
      data: 65.37310791015625
    UKIAH CA SOLAR RADIATION USAF-NOAA:
      dims: []
      attrs: {}
      data: 199.2904510498047
    UKIAH CA TEMPERATURE USAF-NOAA:
      dims: []
      attrs: {}
      data: 58.00788879394531
    UKIAH CA WINDSPEED USAF-NOAA:
      dims: []
      attrs: {}
      data: 3.9074223041534424
