xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    EF RUSSIAN 20 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR:
      dims: []
      attrs: {}
      data: 0.00825346540659666
    EF RUSSIAN 20 PRECIP-INC SCREENED:
      dims: []
      attrs: {}
      data: 0.0275993924587965
    NR CALPELLA FLOW COE CPL:
      dims: []
      attrs: {}
      data: 642.691162109375
    POTTER VALLEY CA FLOW USGS_ADJUSTED:
      dims: []
      attrs: {}
      data: 100.12418365478516
    UKIAH CA HUMIDITY USAF-NOAA:
      dims: []
      attrs: {}
      data: 22.224559783935547
    UKIAH CA SOLAR RADIATION USAF-NOAA:
      dims: []
      attrs: {}
      data: 294.3392639160156
    UKIAH CA TEMPERATURE USAF-NOAA:
      dims: []
      attrs: {}
      data: 14.280900955200195
    UKIAH CA WINDSPEED USAF-NOAA:
      dims: []
      attrs: {}
      data: 4.319703578948975
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    EF RUSSIAN 20 ET-POTENTIAL RUN:BASIN AVERAGE 60 YR:
      dims: []
      attrs: {}
      data: 0.004703705199062824
    EF RUSSIAN 20 PRECIP-INC SCREENED:
      dims: []
      attrs: {}
      data: 0.005687368102371693
    NR CALPELLA FLOW COE CPL:
      dims: []
      attrs: {}
      data: 345.8992919921875
    POTTER VALLEY CA FLOW USGS_ADJUSTED:
      dims: []
      attrs: {}
      data: 154.9901885986328
    UKIAH CA HUMIDITY USAF-NOAA:
      dims: []
      attrs: {}
      data: 65.63752746582031
    UKIAH CA SOLAR RADIATION USAF-NOAA:
      dims: []
      attrs: {}
      data: 189.1494598388672
    UKIAH CA TEMPERATURE USAF-NOAA:
      dims: []
      attrs: {}
      data: 58.30524444580078
    UKIAH CA WINDSPEED USAF-NOAA:
      dims: []
      attrs: {}
      data: 3.5719356536865234
